# Install Node.js using packages crafted by NodeSource
---
- name: Download the nodejs install script
  get_url: url=https://deb.nodesource.com/setup_{{ node_version }} dest=/tmp/setup_nodejs_{{ node_version }}.sh

- name: Execute the nodejs install script
  become: yes
  shell: bash setup_nodejs_{{ node_version }}.sh chdir=/tmp executable=/bin/bash

- name: Install Node.js
  apt:
    pkg:
      - nodejs
    state: installed
    update_cache: yes

- name: Install global packages
  npm: 
    name: "{{ item }}"
    global: yes
    state: present
  with_items: "{{ npm_packages }}"
