---

- name: Update cache
  apt: update_cache=yes

- name: Install system packages
  apt: pkg={{ item }} state=installed
  with_items:
      - python3-pip

- name: Update pip
  pip: name=pip state=latest