---
- name: Download Zeppelin package
  get_url: 
    url: "{{ zeppelin_package_url }}"
    dest: "~{{ zeppelin_user }}/downloads"
    owner: "{{ zeppelin_user }}"
    group: "{{ zeppelin_user }}"

- name: Unpack Zeppelin package
  unarchive:
    src: "~{{ zeppelin_user }}/downloads/{{ zeppelin_package_url | basename }}"
    dest: /opt/
    owner: "{{ zeppelin_user }}"
    group: "{{ zeppelin_user }}"
    remote_src: True

- name: Set link to zeppelin directory
  file:
    src: "/opt/{{ zeppelin_package_url | basename　| splitext | first }}"
    dest: "{{ zeppelin_home }}"
    owner: "{{ zeppelin_user }}"
    group: "{{ zeppelin_user }}"
    state: link
    force: yes


# For python interpreter(matplotlib)
- name: Superset | Install system packages
  action: apt pkg={{ item }} state=installed
  with_items:
    - python3-tk

# For python interpreter
- name: Zeppelin | Install python packages
  become: True
  pip:
    name: "{{ item }}"
    state: latest
    extra_args: -i https://pypi.douban.com/simple/
    executable: pip3
  with_items:
    - py4j
    - matplotlib
    - pandas
    - pandasql

- name: Install zeppelin interpreters
  command: "{{ zeppelin_home }}/bin/install-interpreter.sh --name {{ item }}"
  with_items:
    - cassandra
    - angular
    - elasticsearch
    - file
    - jdbc
    - livy
    - md
    - python
    - shell

- name: Copy zeppelin config
  template: 
    src: "opt/zeppelin/conf/zeppelin-env.sh"
    dest: "{{ zeppelin_home }}/conf/zeppelin-env.sh"
    owner: "{{ zeppelin_user }}"
    group: "{{ zeppelin_user }}"
    mode: "0644"

- name: Set zeppelin Service
  become: yes
  template: 
    src: "etc/systemd/system/zeppelin.service"
    dest: "/etc/systemd/system/zeppelin.service"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Enable zeppelin Service
  become: yes
  systemd:
    name: "zeppelin.service"
    enabled: yes