---
- name: Creates Airflow Home Directory
  become: yes
  file:
    path: "{{ airflow_home }}"
    state: directory
    owner: "{{ airflow_user }}"
    group: "{{ airflow_user }}"
    mode: 'g+rwx'

- name: Set Airflow Profile
  become: yes
  template: 
    src: "etc/profile.d/airflow.sh"
    dest: "/etc/profile.d/airflow.sh"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Set Sudoers
  become: yes
  template: 
    src: "etc/sudoers.d/airflow" 
    dest: "/etc/sudoers.d/airflow"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Set Airflow Service
  become: yes
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - { src: etc/systemd/system/airflow-webserver.service, dest: /etc/systemd/system/airflow-webserver.service }
    - { src: etc/systemd/system/airflow-scheduler.service, dest: /etc/systemd/system/airflow-scheduler.service }

- name: Enable Airflow Service
  become: yes
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: restarted
  with_items:
    - airflow-webserver.service
    - airflow-scheduler.service

# Rest of tasks
# Deploy Application Code via Jenkins
# Set hosts
# Init DB