---
- name: Deploy airflow
  hosts: job-servers
  gather_facts: False
  become: yes
  roles:
    - zeppelin
  vars:
    zeppelin_user: vertica
    package_url: http://mirrors.hust.edu.cn/apache/zeppelin/zeppelin-0.7.1/zeppelin-0.7.1-bin-netinst.tgz