---
- name: Deploy Zeppelin
  hosts: job-servers
  gather_facts: False
  become: yes
  roles:
    - zeppelin
  vars:
    zeppelin_user: vertica
    zeppelin_package_url: http://mirrors.hust.edu.cn/apache/zeppelin/zeppelin-0.7.3/zeppelin-0.7.3-bin-netinst.tgz
    zeppelin_home: /opt/zeppelin